nix: kernel-xilinx: bump to latest master
This includes most patches sent upstream - we're down to the
`__aeabi_[u]ldivmod` and
"undefined reference to `xlnx_bridge_helper_{fini,init}'"
errors.